/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProxyKind = "none" | "game_guard";

export const ProxyKind = {
    None: "none",
    GameGuard: "game_guard",
} as const;
