/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Rivet from "../../api/index";
import * as core from "../../core";

export const StringTcpAddressHashableMapValue: core.serialization.ObjectSchema<
    serializers.StringTcpAddressHashableMapValue.Raw,
    Rivet.StringTcpAddressHashableMapValue
> = core.serialization.object({
    hostname: core.serialization.string(),
    port: core.serialization.number(),
});

export declare namespace StringTcpAddressHashableMapValue {
    export interface Raw {
        hostname: string;
        port: number;
    }
}
