/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";
import { kv } from "../../index";
export declare const PutBatchRequest: core.serialization.ObjectSchema<serializers.kv.PutBatchRequest.Raw, Rivet.kv.PutBatchRequest>;
export declare namespace PutBatchRequest {
    interface Raw {
        namespace_id?: string | null;
        entries: kv.PutEntry.Raw[];
    }
}
