/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";
import { kv } from "../../index";
export declare const PutRequest: core.serialization.ObjectSchema<serializers.kv.PutRequest.Raw, Rivet.kv.PutRequest>;
export declare namespace PutRequest {
    interface Raw {
        namespace_id?: string | null;
        key: kv.Key.Raw;
        value?: kv.Value.Raw;
    }
}
