/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         project: "string",
 *         environment: "string",
 *         queryJson: "string"
 *     }
 */
export interface ExportActorLogsRequest {
    project?: string;
    environment?: string;
    /** JSON-encoded query expression for filtering logs */
    queryJson: string;
}
