/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of cluster that the backend is currently running.
 */
export type BootstrapCluster = "enterprise" | "oss";

export const BootstrapCluster = {
    Enterprise: "enterprise",
    Oss: "oss",
} as const;
