/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../index";
import * as Rivet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
export declare const Header: core.serialization.ObjectSchema<serializers.cloud.version.cdn.Header.Raw, Rivet.cloud.version.cdn.Header>;
export declare namespace Header {
    interface Raw {
        name: string;
        value: string;
    }
}
