/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../../index";

export interface Allocation {
    single?: Rivet.builds.AllocationSingle;
    multi?: Rivet.builds.AllocationMulti;
}
