/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../..";

export interface GameLogoUploadPrepareResponse {
    uploadId: string;
    presignedRequest: Rivet.upload.PresignedRequest;
}
