[package]
name = "nomad-monitor"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client.workspace = true
chirp-workflow.workspace = true
chrono = "0.4"
futures-util = "0.3"
indoc = "1.0"
lazy_static = "1.4"
nomad-util.workspace = true
prost = "0.10"
rivet-connection.workspace = true
rivet-health-checks.workspace = true
rivet-metrics.workspace = true
rivet-operation.workspace = true
rivet-pools.workspace = true
rivet-runtime.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
tracing-logfmt = "0.3"
util-job.workspace = true

cluster.workspace = true
rivet-config.workspace = true

[dependencies.nomad_client]
workspace = true

[dev-dependencies]
chirp-worker.workspace = true
