/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { actor } from "../../../../index";
export declare const GameGuardRouting: core.serialization.ObjectSchema<serializers.actor.GameGuardRouting.Raw, Rivet.actor.GameGuardRouting>;
export declare namespace GameGuardRouting {
    interface Raw {
        authorization?: actor.PortAuthorization.Raw | null;
    }
}
