/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { PortProtocol } from "./PortProtocol";
import { PortRouting } from "./PortRouting";

export const Port: core.serialization.ObjectSchema<serializers.actor.Port.Raw, Rivet.actor.Port> =
    core.serialization.object({
        protocol: PortProtocol,
        internalPort: core.serialization.property("internal_port", core.serialization.number().optional()),
        publicHostname: core.serialization.property("public_hostname", core.serialization.string().optional()),
        publicPort: core.serialization.property("public_port", core.serialization.number().optional()),
        routing: PortRouting,
    });

export declare namespace Port {
    interface Raw {
        protocol: PortProtocol.Raw;
        internal_port?: number | null;
        public_hostname?: string | null;
        public_port?: number | null;
        routing: PortRouting.Raw;
    }
}
