/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { AuthAgentIdentity } from "./AuthAgentIdentity";
import { AuthAgentGameCloud } from "./AuthAgentGameCloud";

export const AuthAgent: core.serialization.ObjectSchema<serializers.cloud.AuthAgent.Raw, Rivet.cloud.AuthAgent> =
    core.serialization.object({
        identity: AuthAgentIdentity.optional(),
        gameCloud: core.serialization.property("game_cloud", AuthAgentGameCloud.optional()),
    });

export declare namespace AuthAgent {
    export interface Raw {
        identity?: AuthAgentIdentity.Raw | null;
        game_cloud?: AuthAgentGameCloud.Raw | null;
    }
}
