/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BuildDeliveryMethod = "traffic_server" | "s3_direct";

export const BuildDeliveryMethod = {
    TrafficServer: "traffic_server",
    S3Direct: "s3_direct",
} as const;
