/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../index";
import * as Rivet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { common } from "../../../../../../index";
export declare const CompleteAccessTokenVerificationRequest: core.serialization.ObjectSchema<serializers.auth.identity.CompleteAccessTokenVerificationRequest.Raw, Rivet.auth.identity.CompleteAccessTokenVerificationRequest>;
export declare namespace CompleteAccessTokenVerificationRequest {
    interface Raw {
        access_token: common.Jwt.Raw;
    }
}
