[package]
name = "api-job"
version = "0.0.1"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
api-helper = { path = "../../../lib/api-helper/build" }
async-trait = "0.1"
chirp-client = { path = "../../../lib/chirp/client" }
rivet-operation = { path = "../../../lib/operation/core" }
chrono = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
lazy_static = "1.4"
prost = "0.10"
rivet-cache = { path = "../../../lib/cache/build" }
rivet-claims = { path = "../../../lib/claims" }
rivet-health-checks = { path = "../../../lib/health-checks" }
rivet-job-server = { path = "../../../lib/smithy-output/api-job/rust-server" }
rivet-pools = { path = "../../../lib/pools" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.29" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
url = "2.2.2"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
rivet-connection = { path = "../../../lib/connection" }
rivet-job = { path = "../../../lib/smithy-output/api-job/rust" }
reqwest = "0.11"
nomad-util = { path = "../../../lib/nomad-util" }
nomad-client = "0.0.9"

faker-job-run = { path = "../../pkg/faker/ops/job-run" }
job-run = { path = "../../pkg/job-run" }
token-create = { path = "../../pkg/token/ops/create" }
