# TODO:
resource "kubernetes_namespace" "redis" {
	for_each = var.redis_dbs

	metadata {
		name = "redis-${each.key}"
	}
}

resource "random_password" "root_password" {
	for_each = var.redis_dbs

	length = 32
	special = false
}

resource "helm_release" "redis" {
	for_each = var.redis_dbs

	name = "redis"
	namespace = kubernetes_namespace.redis[each.key].metadata.0.name
	repository = "https://charts.bitnami.com/bitnami"
	chart = "redis"
	version = "17.14.6"
	values = [yamlencode({
		global = {
			storageClass = var.k8s_storage_class
			redis = {
				password = random_password.root_password[each.key].result
			}
		}
		replica = {
			replicaCount = 1
		}
		auth = {
			enable = true
		}
		metrics = {
			enabled = true
		}
		tls = {
			enable = true
			authClients = true
			autoGenerated = true
		}
	})]
}

data "kubernetes_config_map" "root_ca" {
	for_each = var.redis_dbs

	depends_on = [helm_release.redis]

	metadata {
		name = "kube-root-ca.crt"
		namespace = kubernetes_namespace.redis[each.key].metadata.0.name
	}
}

