/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";
import { Server } from "../resources/common/types/Server";

export const CreateServerResponse: core.serialization.ObjectSchema<
    serializers.servers.CreateServerResponse.Raw,
    Rivet.servers.CreateServerResponse
> = core.serialization.object({
    server: Server,
});

export declare namespace CreateServerResponse {
    export interface Raw {
        server: Server.Raw;
    }
}
