/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";
import { group, common } from "../../index";
export declare const GetBansResponse: core.serialization.ObjectSchema<serializers.group.GetBansResponse.Raw, Rivet.group.GetBansResponse>;
export declare namespace GetBansResponse {
    interface Raw {
        banned_identities: group.BannedIdentity.Raw[];
        anchor?: string | null;
        watch: common.WatchResponse.Raw;
    }
}
