/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";
import { group, common } from "../../index";
export declare const ListSuggestedResponse: core.serialization.ObjectSchema<serializers.group.ListSuggestedResponse.Raw, Rivet.group.ListSuggestedResponse>;
export declare namespace ListSuggestedResponse {
    interface Raw {
        groups: group.Summary.Raw[];
        watch: common.WatchResponse.Raw;
    }
}
