/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";
import { group } from "../../index";
export declare const SearchResponse: core.serialization.ObjectSchema<serializers.group.SearchResponse.Raw, Rivet.group.SearchResponse>;
export declare namespace SearchResponse {
    interface Raw {
        groups: group.Handle.Raw[];
        anchor?: string | null;
    }
}
