/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";
import { common, group } from "../../index";
export declare const ValidateProfileRequest: core.serialization.ObjectSchema<serializers.group.ValidateProfileRequest.Raw, Rivet.group.ValidateProfileRequest>;
export declare namespace ValidateProfileRequest {
    interface Raw {
        display_name?: common.DisplayName.Raw | null;
        bio?: common.DisplayName.Raw | null;
        publicity?: group.Publicity.Raw | null;
    }
}
