/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Rivet from "../../../../../../api";
import * as core from "../../../../../../core";

export const CdnSiteSummary: core.serialization.ObjectSchema<
    serializers.cloud.CdnSiteSummary.Raw,
    Rivet.cloud.CdnSiteSummary
> = core.serialization.object({
    siteId: core.serialization.property("site_id", core.serialization.string()),
    uploadId: core.serialization.property("upload_id", core.serialization.string()),
    displayName: core.serialization.property(
        "display_name",
        core.serialization.lazy(async () => (await import("../../../../..")).DisplayName)
    ),
    createTs: core.serialization.property(
        "create_ts",
        core.serialization.lazy(async () => (await import("../../../../..")).Timestamp)
    ),
    contentLength: core.serialization.property("content_length", core.serialization.number()),
    complete: core.serialization.boolean(),
});

export declare namespace CdnSiteSummary {
    interface Raw {
        site_id: string;
        upload_id: string;
        display_name: serializers.DisplayName.Raw;
        create_ts: serializers.Timestamp.Raw;
        content_length: number;
        complete: boolean;
    }
}
