/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Rivet from "../../../../../../api";
import * as core from "../../../../../../core";

export const LogsPerfMark: core.serialization.ObjectSchema<
    serializers.cloud.LogsPerfMark.Raw,
    Rivet.cloud.LogsPerfMark
> = core.serialization.object({
    label: core.serialization.string(),
    ts: core.serialization.lazy(async () => (await import("../../../../..")).Timestamp),
    rayId: core.serialization.property("ray_id", core.serialization.string().optional()),
    reqId: core.serialization.property("req_id", core.serialization.string().optional()),
});

export declare namespace LogsPerfMark {
    interface Raw {
        label: string;
        ts: serializers.Timestamp.Raw;
        ray_id?: string | null;
        req_id?: string | null;
    }
}
