/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const RegionTierExpenses: core.serialization.ObjectSchema<
    serializers.cloud.RegionTierExpenses.Raw,
    Rivet.cloud.RegionTierExpenses
> = core.serialization.object({
    namespaceId: core.serialization.property("namespace_id", core.serialization.string()),
    regionId: core.serialization.property("region_id", core.serialization.string()),
    tierNameId: core.serialization.property("tier_name_id", core.serialization.string()),
    lobbyGroupNameId: core.serialization.property("lobby_group_name_id", core.serialization.string()),
    uptime: core.serialization.number(),
    expenses: core.serialization.number(),
});

export declare namespace RegionTierExpenses {
    interface Raw {
        namespace_id: string;
        region_id: string;
        tier_name_id: string;
        lobby_group_name_id: string;
        uptime: number;
        expenses: number;
    }
}
