/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { common } from "../../../../index";
export declare const LobbySummaryAnalytics: core.serialization.ObjectSchema<serializers.cloud.LobbySummaryAnalytics.Raw, Rivet.cloud.LobbySummaryAnalytics>;
export declare namespace LobbySummaryAnalytics {
    interface Raw {
        lobby_id: string;
        lobby_group_id: string;
        lobby_group_name_id: string;
        region_id: string;
        create_ts: common.Timestamp.Raw;
        is_ready: boolean;
        is_idle: boolean;
        is_closed: boolean;
        is_outdated: boolean;
        max_players_normal: number;
        max_players_direct: number;
        max_players_party: number;
        total_player_count: number;
        registered_player_count: number;
    }
}
