/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { common } from "../../../../index";
export declare const LogsPerfMark: core.serialization.ObjectSchema<serializers.cloud.LogsPerfMark.Raw, Rivet.cloud.LogsPerfMark>;
export declare namespace LogsPerfMark {
    interface Raw {
        label: string;
        ts: common.Timestamp.Raw;
        ray_id?: string | null;
        req_id?: string | null;
    }
}
