/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../index";
import * as Rivet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { cloud } from "../../../../../../index";
export declare const GetGameVersionByIdResponse: core.serialization.ObjectSchema<serializers.cloud.games.GetGameVersionByIdResponse.Raw, Rivet.cloud.games.GetGameVersionByIdResponse>;
export declare namespace GetGameVersionByIdResponse {
    interface Raw {
        version: cloud.version.Full.Raw;
    }
}
