/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";
import { BootstrapCaptchaTurnstile } from "./BootstrapCaptchaTurnstile";

export const BootstrapCaptcha: core.serialization.ObjectSchema<
    serializers.cloud.BootstrapCaptcha.Raw,
    Rivet.cloud.BootstrapCaptcha
> = core.serialization.object({
    turnstile: BootstrapCaptchaTurnstile.optional(),
});

export declare namespace BootstrapCaptcha {
    export interface Raw {
        turnstile?: BootstrapCaptchaTurnstile.Raw | null;
    }
}
