/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RunnerConfigsUpsertRequestServerless {
    maxRunners: number;
    minRunners: number;
    /** Seconds. */
    requestLifespan: number;
    runnersMargin: number;
    slotsPerRunner: number;
    url: string;
}
