/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../..";
import * as Rivet from "../../../../../../../../api";
import * as core from "../../../../../../../../core";
export declare const CreateGameNamespaceTokenDevelopmentRequest: core.serialization.ObjectSchema<serializers.cloud.games.namespaces.CreateGameNamespaceTokenDevelopmentRequest.Raw, Rivet.cloud.games.namespaces.CreateGameNamespaceTokenDevelopmentRequest>;
export declare namespace CreateGameNamespaceTokenDevelopmentRequest {
    interface Raw {
        hostname: string;
        ports?: Record<string, serializers.cloud.MatchmakerDevelopmentPort.Raw> | null;
        lobby_ports?: serializers.cloud.version.matchmaker.LobbyGroupRuntimeDockerPort.Raw[] | null;
    }
}
