/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../..";
import * as Rivet from "../../../../../../../../api";
import * as core from "../../../../../../../../core";
export declare const ValidateGameNamespaceMatchmakerConfigRequest: core.serialization.ObjectSchema<serializers.cloud.games.namespaces.ValidateGameNamespaceMatchmakerConfigRequest.Raw, Rivet.cloud.games.namespaces.ValidateGameNamespaceMatchmakerConfigRequest>;
export declare namespace ValidateGameNamespaceMatchmakerConfigRequest {
    interface Raw {
        lobby_count_max: number;
        max_players: number;
    }
}
