/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../..";
import * as Rivet from "../../../../../../../../api";
import * as core from "../../../../../../../../core";
export declare const ValidateGameNamespaceMatchmakerConfigResponse: core.serialization.ObjectSchema<serializers.cloud.games.namespaces.ValidateGameNamespaceMatchmakerConfigResponse.Raw, Rivet.cloud.games.namespaces.ValidateGameNamespaceMatchmakerConfigResponse>;
export declare namespace ValidateGameNamespaceMatchmakerConfigResponse {
    interface Raw {
        errors: serializers.ValidationError.Raw[];
    }
}
