/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../../index";

export interface Container {
    id: Rivet.Id;
    region: string;
    tags?: unknown;
    runtime: Rivet.containers.Runtime;
    network: Rivet.containers.Network;
    resources: Rivet.containers.Resources;
    lifecycle: Rivet.containers.Lifecycle;
    createdAt: Rivet.Timestamp;
    startedAt?: Rivet.Timestamp;
    destroyedAt?: Rivet.Timestamp;
}
