*

!Cargo.lock
!Cargo.toml
!sdks/full/rust/Cargo.toml
!sdks/full/rust/src
!packages
!resources/legacy/proto

!docker/dev-monolith
docker/dev-monolith/Dockerfile
docker/dev-monolith/Dockerfile.dockerignore
docker/dev-monolith/*.md

sdks/runtime
svc/**/*.md

