/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Rivet from "../../..";
import { Invites } from "../resources/invites/client/Client";
import { JoinRequests } from "../resources/joinRequests/client/Client";
export declare namespace Group {
    interface Options {
        environment?: core.Supplier<environments.RivetEnvironment | string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Group {
    protected readonly _options: Group.Options;
    constructor(_options?: Group.Options);
    /**
     * Returns a list of suggested groups.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    listSuggested(request?: Rivet.group.ListSuggestedRequest, requestOptions?: Group.RequestOptions): Promise<Rivet.group.ListSuggestedResponse>;
    /**
     * Creates a new group.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    create(request: Rivet.group.CreateRequest, requestOptions?: Group.RequestOptions): Promise<Rivet.group.CreateResponse>;
    /**
     * Prepares an avatar image upload.
     * Complete upload with `rivet.api.group#CompleteAvatarUpload`.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    prepareAvatarUpload(request: Rivet.group.PrepareAvatarUploadRequest, requestOptions?: Group.RequestOptions): Promise<Rivet.group.PrepareAvatarUploadResponse>;
    /**
     * Validate contents of group profile. Use to provide immediate feedback on profile changes before committing them.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    validateProfile(request: Rivet.group.ValidateProfileRequest, requestOptions?: Group.RequestOptions): Promise<Rivet.group.ValidateProfileResponse>;
    /**
     * Fuzzy search for groups.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    search(request: Rivet.group.SearchRequest, requestOptions?: Group.RequestOptions): Promise<Rivet.group.SearchResponse>;
    /**
     * Completes an avatar image upload. Must be called after the file upload
     * process completes.
     * Call `rivet.api.group#PrepareAvatarUpload` first.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    completeAvatarUpload(groupId: string, uploadId: string, requestOptions?: Group.RequestOptions): Promise<void>;
    /**
     * Returns a group's bans. Must have valid permissions to view.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    getBans(groupId: string, request?: Rivet.group.GetBansRequest, requestOptions?: Group.RequestOptions): Promise<Rivet.group.GetBansResponse>;
    /**
     * Bans an identity from a group. Must be the owner of the group to perform this action. The banned identity will no longer be able to create a join request or use a group invite.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    banIdentity(groupId: string, identityId: string, requestOptions?: Group.RequestOptions): Promise<void>;
    /**
     * Unbans an identity from a group. Must be the owner of the group to perform this action.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    unbanIdentity(groupId: string, identityId: string, requestOptions?: Group.RequestOptions): Promise<void>;
    /**
     * Returns a group's join requests. Must have valid permissions to view.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    getJoinRequests(groupId: string, request?: Rivet.group.GetJoinRequestsRequest, requestOptions?: Group.RequestOptions): Promise<Rivet.group.GetJoinRequestsResponse>;
    /**
     * Kicks an identity from a group. Must be the owner of the group to perform this action.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    kickMember(groupId: string, identityId: string, requestOptions?: Group.RequestOptions): Promise<void>;
    /**
     * Leaves a group.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    leave(groupId: string, requestOptions?: Group.RequestOptions): Promise<void>;
    /**
     * Returns a group's members.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    getMembers(groupId: string, request?: Rivet.group.GetMembersRequest, requestOptions?: Group.RequestOptions): Promise<Rivet.group.GetMembersResponse>;
    /**
     * Returns a group profile.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    getProfile(groupId: string, request?: Rivet.group.GetProfileRequest, requestOptions?: Group.RequestOptions): Promise<Rivet.group.GetProfileResponse>;
    /**
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    updateProfile(groupId: string, request: Rivet.group.UpdateProfileRequest, requestOptions?: Group.RequestOptions): Promise<void>;
    /**
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    getSummary(groupId: string, requestOptions?: Group.RequestOptions): Promise<Rivet.group.GetSummaryResponse>;
    /**
     * Transfers ownership of a group to another identity.
     * @throws {@link Rivet.InternalError}
     * @throws {@link Rivet.RateLimitError}
     * @throws {@link Rivet.ForbiddenError}
     * @throws {@link Rivet.UnauthorizedError}
     * @throws {@link Rivet.NotFoundError}
     * @throws {@link Rivet.BadRequestError}
     */
    transferOwnership(groupId: string, request: Rivet.group.TransferOwnershipRequest, requestOptions?: Group.RequestOptions): Promise<void>;
    protected _invites: Invites | undefined;
    get invites(): Invites;
    protected _joinRequests: JoinRequests | undefined;
    get joinRequests(): JoinRequests;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
