/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CloudLobbySummaryAnalytics : Analytical information about a lobby.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudLobbySummaryAnalytics {
    /// RFC3339 timestamp
    #[serde(rename = "create_ts")]
    pub create_ts: String,
    /// Whether or not this lobby is in a closed state.
    #[serde(rename = "is_closed")]
    pub is_closed: bool,
    /// Whether or not this lobby is idle.
    #[serde(rename = "is_idle")]
    pub is_idle: bool,
    /// Whether or not this lobby is outdated.
    #[serde(rename = "is_outdated")]
    pub is_outdated: bool,
    /// Whether or not this lobby is ready.
    #[serde(rename = "is_ready")]
    pub is_ready: bool,
    #[serde(rename = "lobby_group_id")]
    pub lobby_group_id: uuid::Uuid,
    /// A human readable short identifier used to references resources. Different than a `rivet.common#Uuid` because this is intended to be human readable. Different than `rivet.common#DisplayName` because this should not include special characters and be short.
    #[serde(rename = "lobby_group_name_id")]
    pub lobby_group_name_id: String,
    #[serde(rename = "lobby_id")]
    pub lobby_id: uuid::Uuid,
    /// Unsigned 32 bit integer.
    #[serde(rename = "max_players_direct")]
    pub max_players_direct: i32,
    /// Unsigned 32 bit integer.
    #[serde(rename = "max_players_normal")]
    pub max_players_normal: i32,
    /// Unsigned 32 bit integer.
    #[serde(rename = "max_players_party")]
    pub max_players_party: i32,
    #[serde(rename = "region_id")]
    pub region_id: uuid::Uuid,
    /// Unsigned 32 bit integer.
    #[serde(rename = "registered_player_count")]
    pub registered_player_count: i32,
    /// Unsigned 32 bit integer.
    #[serde(rename = "total_player_count")]
    pub total_player_count: i32,
}

impl CloudLobbySummaryAnalytics {
    /// Analytical information about a lobby.
    pub fn new(create_ts: String, is_closed: bool, is_idle: bool, is_outdated: bool, is_ready: bool, lobby_group_id: uuid::Uuid, lobby_group_name_id: String, lobby_id: uuid::Uuid, max_players_direct: i32, max_players_normal: i32, max_players_party: i32, region_id: uuid::Uuid, registered_player_count: i32, total_player_count: i32) -> CloudLobbySummaryAnalytics {
        CloudLobbySummaryAnalytics {
            create_ts,
            is_closed,
            is_idle,
            is_outdated,
            is_ready,
            lobby_group_id,
            lobby_group_name_id,
            lobby_id,
            max_players_direct,
            max_players_normal,
            max_players_party,
            region_id,
            registered_player_count,
            total_player_count,
        }
    }
}


