/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CloudVersionMatchmakerGameModeRegion : A game mode region.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudVersionMatchmakerGameModeRegion {
    #[serde(rename = "idle_lobbies", skip_serializing_if = "Option::is_none")]
    pub idle_lobbies: Option<Box<crate::models::CloudVersionMatchmakerGameModeIdleLobbiesConfig>>,
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<String>,
}

impl CloudVersionMatchmakerGameModeRegion {
    /// A game mode region.
    pub fn new() -> CloudVersionMatchmakerGameModeRegion {
        CloudVersionMatchmakerGameModeRegion {
            idle_lobbies: None,
            tier: None,
        }
    }
}


