/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServersServersCreateRequest {
    /// The name id of the cluster
    #[serde(rename = "cluster")]
    pub cluster: String,
    /// The name id of the datacenter
    #[serde(rename = "datacenter")]
    pub datacenter: String,
    #[serde(rename = "kill_timeout")]
    pub kill_timeout: i32,
    #[serde(rename = "metadata")]
    pub metadata: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "runtime")]
    pub runtime: Box<crate::models::ServersRuntime>,
}

impl ServersServersCreateRequest {
    pub fn new(cluster: String, datacenter: String, kill_timeout: i32, metadata: ::std::collections::HashMap<String, serde_json::Value>, runtime: crate::models::ServersRuntime) -> ServersServersCreateRequest {
        ServersServersCreateRequest {
            cluster,
            datacenter,
            kill_timeout,
            metadata,
            runtime: Box::new(runtime),
        }
    }
}


