/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../index";
import * as Rivet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { cloud } from "../../../../../../index";
export declare const ListGameCdnSitesResponse: core.serialization.ObjectSchema<serializers.cloud.games.ListGameCdnSitesResponse.Raw, Rivet.cloud.games.ListGameCdnSitesResponse>;
export declare namespace ListGameCdnSitesResponse {
    interface Raw {
        sites: cloud.CdnSiteSummary.Raw[];
    }
}
