/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Rivet from "../../../../../index";
export interface GlobalEventKind {
    identityUpdate?: Rivet.identity.GlobalEventIdentityUpdate;
    matchmakerLobbyJoin?: Rivet.identity.GlobalEventMatchmakerLobbyJoin;
}
