/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Rivet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { DisplayName } from "../../../../../../common/types/DisplayName";
import { PrepareFile } from "../../../../../../upload/resources/common/types/PrepareFile";

export const CreateGameCdnSiteRequest: core.serialization.ObjectSchema<
    serializers.cloud.games.CreateGameCdnSiteRequest.Raw,
    Rivet.cloud.games.CreateGameCdnSiteRequest
> = core.serialization.object({
    displayName: core.serialization.property("display_name", DisplayName),
    files: core.serialization.list(PrepareFile),
});

export declare namespace CreateGameCdnSiteRequest {
    interface Raw {
        display_name: DisplayName.Raw;
        files: PrepareFile.Raw[];
    }
}
