/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Rivet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { CdnSiteSummary } from "../../../../common/types/CdnSiteSummary";

export const ListGameCdnSitesResponse: core.serialization.ObjectSchema<
    serializers.cloud.games.ListGameCdnSitesResponse.Raw,
    Rivet.cloud.games.ListGameCdnSitesResponse
> = core.serialization.object({
    sites: core.serialization.list(CdnSiteSummary),
});

export declare namespace ListGameCdnSitesResponse {
    export interface Raw {
        sites: CdnSiteSummary.Raw[];
    }
}
