/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../../index";

export interface ListLobbiesResponse {
    gameModes: Rivet.matchmaker.GameModeInfo[];
    regions: Rivet.matchmaker.RegionInfo[];
    lobbies: Rivet.matchmaker.LobbyInfo[];
}
