pub mod converted;
pub mod generated;
pub mod versioned;

pub const PEGBOARD_DATACENTER_RUNNER_ALLOC_IDX_VERSION: u16 = 1;
pub const PEGBOARD_RUNNER_ADDRESS_VERSION: u16 = 1;
pub const PEGBOARD_RUNNER_METADATA_VERSION: u16 = 1;
pub const PEGBOARD_NAMESPACE_ACTOR_BY_KEY_VERSION: u16 = 1;
pub const PEGBOARD_NAMESPACE_RUNNER_BY_KEY_VERSION: u16 = 1;
pub const PEGBOARD_NAMESPACE_ACTOR_NAME_VERSION: u16 = 1;
