/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NetworkMode = "bridge" | "host";

export const NetworkMode = {
    Bridge: "bridge",
    Host: "host",
} as const;
