/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";
import { ValidationError } from "../../common/types/ValidationError";

export const ValidateProfileResponse: core.serialization.ObjectSchema<
    serializers.group.ValidateProfileResponse.Raw,
    Rivet.group.ValidateProfileResponse
> = core.serialization.object({
    errors: core.serialization.list(ValidationError),
});

export declare namespace ValidateProfileResponse {
    export interface Raw {
        errors: ValidationError.Raw[];
    }
}
