/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Rivet from "../../../../../../..";
export interface CreateDatacenterRequest {
    displayName: string;
    nameId: string;
    provider: Rivet.admin.clusters.Provider;
    providerDatacenterId: string;
    buildDeliveryMethod: Rivet.admin.clusters.BuildDeliveryMethod;
}
