/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminClustersUpdateDatacenterRequest {
    #[serde(rename = "pools")]
    pub pools: Vec<crate::models::AdminClustersPoolUpdate>,
    #[serde(rename = "prebakes_enabled", skip_serializing_if = "Option::is_none")]
    pub prebakes_enabled: Option<bool>,
}

impl AdminClustersUpdateDatacenterRequest {
    pub fn new(pools: Vec<crate::models::AdminClustersPoolUpdate>) -> AdminClustersUpdateDatacenterRequest {
        AdminClustersUpdateDatacenterRequest {
            pools,
            prebakes_enabled: None,
        }
    }
}


