/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminClustersDatacenter {
    #[serde(rename = "build_delivery_method")]
    pub build_delivery_method: crate::models::AdminClustersBuildDeliveryMethod,
    #[serde(rename = "cluster_id")]
    pub cluster_id: uuid::Uuid,
    #[serde(rename = "datacenter_id")]
    pub datacenter_id: uuid::Uuid,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "name_id")]
    pub name_id: String,
    #[serde(rename = "pools")]
    pub pools: Vec<crate::models::AdminClustersPool>,
    #[serde(rename = "provider")]
    pub provider: crate::models::AdminClustersProvider,
    #[serde(rename = "provider_api_token", skip_serializing_if = "Option::is_none")]
    pub provider_api_token: Option<String>,
    #[serde(rename = "provider_datacenter_id")]
    pub provider_datacenter_id: String,
}

impl AdminClustersDatacenter {
    pub fn new(build_delivery_method: crate::models::AdminClustersBuildDeliveryMethod, cluster_id: uuid::Uuid, datacenter_id: uuid::Uuid, display_name: String, name_id: String, pools: Vec<crate::models::AdminClustersPool>, provider: crate::models::AdminClustersProvider, provider_datacenter_id: String) -> AdminClustersDatacenter {
        AdminClustersDatacenter {
            build_delivery_method,
            cluster_id,
            datacenter_id,
            display_name,
            name_id,
            pools,
            provider,
            provider_api_token: None,
            provider_datacenter_id,
        }
    }
}


