/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdminPool {
    #[serde(rename = "desired_count")]
    pub desired_count: i32,
    #[serde(rename = "drain_timeout")]
    pub drain_timeout: i64,
    #[serde(rename = "hardware")]
    pub hardware: Vec<crate::models::AdminHardware>,
    #[serde(rename = "max_count")]
    pub max_count: i32,
    #[serde(rename = "pool_type")]
    pub pool_type: crate::models::AdminPoolType,
}

impl AdminPool {
    pub fn new(desired_count: i32, drain_timeout: i64, hardware: Vec<crate::models::AdminHardware>, max_count: i32, pool_type: crate::models::AdminPoolType) -> AdminPool {
        AdminPool {
            desired_count,
            drain_timeout,
            hardware,
            max_count,
            pool_type,
        }
    }
}


