/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServersDockerNetwork {
    #[serde(rename = "mode")]
    pub mode: crate::models::ServersDockerNetworkMode,
    #[serde(rename = "ports")]
    pub ports: ::std::collections::HashMap<String, crate::models::ServersDockerPort>,
}

impl ServersDockerNetwork {
    pub fn new(mode: crate::models::ServersDockerNetworkMode, ports: ::std::collections::HashMap<String, crate::models::ServersDockerPort>) -> ServersDockerNetwork {
        ServersDockerNetwork {
            mode,
            ports,
        }
    }
}


