/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";

export const PatchBuildTagsRequest: core.serialization.ObjectSchema<
    serializers.builds.PatchBuildTagsRequest.Raw,
    Rivet.builds.PatchBuildTagsRequest
> = core.serialization.object({
    tags: core.serialization.unknown(),
    exclusiveTags: core.serialization.property(
        "exclusive_tags",
        core.serialization.list(core.serialization.string()).optional(),
    ),
});

export declare namespace PatchBuildTagsRequest {
    export interface Raw {
        tags?: unknown;
        exclusive_tags?: string[] | null;
    }
}
