*

!Cargo.lock
!Cargo.toml
!sdks/api/full/rust/Cargo.toml
!sdks/api/full/rust/src
!packages
!resources/legacy/proto

!docker/monolith
docker/monolith/Dockerfile
docker/monolith/Dockerfile.dockerignore
docker/monolith/*.md

sdks/runtime

