[package]
name = "ds-worker"
version = "0.0.1"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../lib/chirp/client" }
chirp-worker = { path = "../../../../lib/chirp/worker" }
chrono = "0.4"
lazy_static = "1.4.0"
nomad-util = { path = "../../../../lib/nomad-util" }
rivet-convert = { path = "../../../../lib/convert" }
rivet-health-checks = { path = "../../../../lib/health-checks" }
rivet-metrics = { path = "../../../../lib/metrics" }
rivet-runtime = { path = "../../../../lib/runtime" }
serde = { version = "1.0", features = ["derive"] }
util-job = { package = "rivet-util-job", path = "../../job/util" }
reqwest = { version = "0.12", features = ["json"] }
region-get = { path = "../../region/ops/get" }
rivet-api = { path = "../../../../sdks/full/rust" }



mm-lobby-get = { path = "../../mm/ops/lobby-get" }
job-run-get = { path = "../../job-run/ops/get" }
ds-server-get = { path = "../ops/server-get" }
mm-config-version-get = { path = "../../mm-config/ops/version-get" }

[dev-dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }

[dependencies.sqlx]
git = "https://github.com/rivet-gg/sqlx"
rev = "08d6e61aa0572e7ec557abbedb72cebb96e1ac5b"
default-features = false

[dependencies.nomad_client]
package = "nomad_client"
git = "https://github.com/rivet-gg/nomad-client"
rev = "abb66bf0c30c7ff5b0c695dae952481c33e538b5" # pragma: allowlist secret
