/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../..";

export interface PrepareGameLinkResponse {
    /** Pass this to `GetGameLink` to get the linking status. Valid for 15 minutes. */
    identityLinkToken: string;
    identityLinkUrl: string;
    expireTs: Rivet.Timestamp;
}
