/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../index";

/**
 * @example
 *     {
 *         namespace: "namespace",
 *         crashPolicy: "restart",
 *         name: "name",
 *         runnerNameSelector: "runner_name_selector"
 *     }
 */
export interface ActorsCreateRequest {
    namespace: string;
    datacenter?: string;
    crashPolicy: Rivet.CrashPolicy;
    input?: string;
    key?: string;
    name: string;
    runnerNameSelector: string;
}
