// This file was auto-generated by Fern from our API Definition.

package identity

import (
	json "encoding/json"
	fmt "fmt"
	sdk "sdk"
	game "sdk/common/game"
	group "sdk/common/group"
	identity "sdk/common/identity"
	core "sdk/core"
)

type ListActivitiesRequest struct {
	WatchIndex sdk.WatchQuery `json:"-"`
}

type ListActivitiesResponse struct {
	Identities       []*identity.Handle `json:"identities,omitempty"`
	Games            []*game.Summary    `json:"games,omitempty"`
	SuggestedGroups  []*group.Summary   `json:"suggested_groups,omitempty"`
	SuggestedPlayers []*identity.Handle `json:"suggested_players,omitempty"`
	Watch            *sdk.WatchResponse `json:"watch,omitempty"`

	_rawJSON json.RawMessage
}

func (l *ListActivitiesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListActivitiesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListActivitiesResponse(value)
	l._rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListActivitiesResponse) String() string {
	if len(l._rawJSON) > 0 {
		if value, err := core.StringifyJSON(l._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
