/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Datacenter {
    #[serde(rename = "datacenter_label")]
    pub datacenter_label: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl Datacenter {
    pub fn new(datacenter_label: i32, name: String, url: String) -> Datacenter {
        Datacenter {
            datacenter_label,
            name,
            url,
        }
    }
}

