/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatacentersListResponse {
    #[serde(rename = "datacenters")]
    pub datacenters: Vec<models::Datacenter>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
}

impl DatacentersListResponse {
    pub fn new(datacenters: Vec<models::Datacenter>, pagination: models::Pagination) -> DatacentersListResponse {
        DatacentersListResponse {
            datacenters,
            pagination: Box::new(pagination),
        }
    }
}

