/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";
export declare const NotificationRegisterFirebaseService: core.serialization.ObjectSchema<serializers.portal.NotificationRegisterFirebaseService.Raw, Rivet.portal.NotificationRegisterFirebaseService>;
export declare namespace NotificationRegisterFirebaseService {
    interface Raw {
        access_key: string;
    }
}
