/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Rivet from "../../../../api";
import * as core from "../../../../core";

export const Bio: core.serialization.Schema<serializers.Bio.Raw, Rivet.Bio> = core.serialization.string();

export declare namespace Bio {
    type Raw = string;
}
