/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Rivet from "../../../../../../api";
import * as core from "../../../../../../core";

export const IdentityNamespaceConfig: core.serialization.ObjectSchema<
    serializers.cloud.IdentityNamespaceConfig.Raw,
    Rivet.cloud.IdentityNamespaceConfig
> = core.serialization.object({});

export declare namespace IdentityNamespaceConfig {
    interface Raw {}
}
