// This file was auto-generated by Fern from our API Definition.

package datacenters

import (
	json "encoding/json"
	fmt "fmt"
	core "sdk/core"
)

type GetTlsResponse struct {
	JobCertPem       string `json:"job_cert_pem"`
	JobPrivateKeyPem string `json:"job_private_key_pem"`

	_rawJSON json.RawMessage
}

func (g *GetTlsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTlsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetTlsResponse(value)
	g._rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetTlsResponse) String() string {
	if len(g._rawJSON) > 0 {
		if value, err := core.StringifyJSON(g._rawJSON); err == nil {
			return value
		}
	}
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
