/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { DisplayName as common$$displayName } from "../../../../common/types/DisplayName";
import { common } from "../../../../index";

export const PlatformLink: core.serialization.ObjectSchema<serializers.game.PlatformLink.Raw, Rivet.game.PlatformLink> =
    core.serialization.object({
        displayName: core.serialization.property("display_name", common$$displayName),
        url: core.serialization.string(),
    });

export declare namespace PlatformLink {
    interface Raw {
        display_name: common.DisplayName.Raw;
        url: string;
    }
}
