// This file was auto-generated by Fern from our API Definition.

package client

import (
	http "net/http"
	actorsclient "sdk/actors/client"
	authclient "sdk/auth/client"
	buildsclient "sdk/builds/client"
	cloudclient "sdk/cloud/client"
	core "sdk/core"
	coreintercomclient "sdk/coreintercom/client"
	edgeintercomclient "sdk/edgeintercom/client"
	gamesclient "sdk/games/client"
	groupclient "sdk/group/client"
	identityclient "sdk/identity/client"
	jobclient "sdk/job/client"
	matchmakerclient "sdk/matchmaker/client"
	portalclient "sdk/portal/client"
	provisionclient "sdk/provision/client"
	regionsclient "sdk/regions/client"
	routesclient "sdk/routes/client"
	serversclient "sdk/servers/client"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Actors       *actorsclient.Client
	Builds       *buildsclient.Client
	Cloud        *cloudclient.Client
	CoreIntercom *coreintercomclient.Client
	EdgeIntercom *edgeintercomclient.Client
	Group        *groupclient.Client
	Identity     *identityclient.Client
	Provision    *provisionclient.Client
	Regions      *regionsclient.Client
	Routes       *routesclient.Client
	Servers      *serversclient.Client
	Auth         *authclient.Client
	Games        *gamesclient.Client
	Job          *jobclient.Client
	Matchmaker   *matchmakerclient.Client
	Portal       *portalclient.Client
}

func NewClient(opts ...core.ClientOption) *Client {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &Client{
		baseURL:      options.BaseURL,
		caller:       core.NewCaller(options.HTTPClient),
		header:       options.ToHeader(),
		Actors:       actorsclient.NewClient(opts...),
		Builds:       buildsclient.NewClient(opts...),
		Cloud:        cloudclient.NewClient(opts...),
		CoreIntercom: coreintercomclient.NewClient(opts...),
		EdgeIntercom: edgeintercomclient.NewClient(opts...),
		Group:        groupclient.NewClient(opts...),
		Identity:     identityclient.NewClient(opts...),
		Provision:    provisionclient.NewClient(opts...),
		Regions:      regionsclient.NewClient(opts...),
		Routes:       routesclient.NewClient(opts...),
		Servers:      serversclient.NewClient(opts...),
		Auth:         authclient.NewClient(opts...),
		Games:        gamesclient.NewClient(opts...),
		Job:          jobclient.NewClient(opts...),
		Matchmaker:   matchmakerclient.NewClient(opts...),
		Portal:       portalclient.NewClient(opts...),
	}
}
