chirp_worker::workers![
	nomad_node_drain_complete,
	datacenter_update,
	nomad_node_registered,
	datacenter_create,
	create,
	server_destroy,
	server_install,
	server_drain,
	server_provision,
	scale,
	server_undrain,
];
