/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../../index";

export interface Route {
    id: string;
    createdAt: Rivet.Timestamp;
    updatedAt: Rivet.Timestamp;
    hostname: string;
    path: string;
    /** Whether to route all subpaths of this path */
    routeSubpaths: boolean;
    /** Whether to remove the path prefix before sending the request to the target. */
    stripPrefix: boolean;
    target: Rivet.routes.RouteTarget;
}
