chirp_worker::workers![
	create,
	create_complete_chat_message_create,
	join_request_create,
	join_request_resolve,
	member_create,
	member_kick,
	member_remove,
	owner_transfer,
	profile_set,
	user_ban,
	user_unban,
];
