/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../index";
import * as Rivet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
export declare const Provider: core.serialization.Schema<serializers.admin.clusters.Provider.Raw, Rivet.admin.clusters.Provider>;
export declare namespace Provider {
    type Raw = "linode";
}
