/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Rivet from "../../../../../../api";
import * as core from "../../../../../../core";

export const Member: core.serialization.ObjectSchema<serializers.group.Member.Raw, Rivet.group.Member> =
    core.serialization.object({
        identity: core.serialization.lazyObject(async () => (await import("../../../../..")).identity.Handle),
    });

export declare namespace Member {
    interface Raw {
        identity: serializers.identity.Handle.Raw;
    }
}
