/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type QueryLogStream = "std_out" | "std_err" | "all";

export const QueryLogStream = {
    StdOut: "std_out",
    StdErr: "std_err",
    All: "all",
} as const;
