/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../..";
import * as Rivet from "../../../../../../../../api";
import * as core from "../../../../../../../../core";
export declare const CompleteEmailVerificationResponse: core.serialization.ObjectSchema<serializers.auth.identity.CompleteEmailVerificationResponse.Raw, Rivet.auth.identity.CompleteEmailVerificationResponse>;
export declare namespace CompleteEmailVerificationResponse {
    interface Raw {
        status: serializers.auth.CompleteStatus.Raw;
    }
}
