// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkResource {
    #[serde(rename = "CIDR", skip_serializing_if = "Option::is_none")]
    pub CIDR: Option<String>,
    #[serde(rename = "DNS", skip_serializing_if = "Option::is_none")]
    pub DNS: Option<Box<crate::models::DnsConfig>>,
    #[serde(rename = "Device", skip_serializing_if = "Option::is_none")]
    pub device: Option<String>,
    #[serde(rename = "DynamicPorts", skip_serializing_if = "Option::is_none")]
    pub dynamic_ports: Option<Vec<crate::models::Port>>,
    #[serde(rename = "Hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "IP", skip_serializing_if = "Option::is_none")]
    pub IP: Option<String>,
    #[serde(rename = "MBits", skip_serializing_if = "Option::is_none")]
    pub m_bits: Option<i32>,
    #[serde(rename = "Mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(rename = "ReservedPorts", skip_serializing_if = "Option::is_none")]
    pub reserved_ports: Option<Vec<crate::models::Port>>,
}

impl NetworkResource {
    pub fn new() -> NetworkResource {
        NetworkResource {
            CIDR: None,
            DNS: None,
            device: None,
            dynamic_ports: None,
            hostname: None,
            IP: None,
            m_bits: None,
            mode: None,
            reserved_ports: None,
        }
    }
}


