// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRequest {
    #[serde(rename = "AllowStale", skip_serializing_if = "Option::is_none")]
    pub allow_stale: Option<bool>,
    #[serde(rename = "AuthToken", skip_serializing_if = "Option::is_none")]
    pub auth_token: Option<String>,
    #[serde(rename = "Context", skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    #[serde(rename = "Filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,
    #[serde(rename = "Headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "Namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "NextToken", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
    #[serde(rename = "Params", skip_serializing_if = "Option::is_none")]
    pub params: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "PerPage", skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i32>,
    #[serde(rename = "Prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "Region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(rename = "Reverse", skip_serializing_if = "Option::is_none")]
    pub reverse: Option<bool>,
    #[serde(rename = "WaitIndex", skip_serializing_if = "Option::is_none")]
    pub wait_index: Option<i32>,
    #[serde(rename = "WaitTime", skip_serializing_if = "Option::is_none")]
    pub wait_time: Option<i64>,
}

impl SearchRequest {
    pub fn new() -> SearchRequest {
        SearchRequest {
            allow_stale: None,
            auth_token: None,
            context: None,
            filter: None,
            headers: None,
            namespace: None,
            next_token: None,
            params: None,
            per_page: None,
            prefix: None,
            region: None,
            reverse: None,
            wait_index: None,
            wait_time: None,
        }
    }
}


