/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../../..";
import * as Rivet from "../../../../../../../../../../api";
import * as core from "../../../../../../../../../../core";
export declare const LobbyGroupRuntimeDockerPort: core.serialization.ObjectSchema<serializers.cloud.version.matchmaker.LobbyGroupRuntimeDockerPort.Raw, Rivet.cloud.version.matchmaker.LobbyGroupRuntimeDockerPort>;
export declare namespace LobbyGroupRuntimeDockerPort {
    interface Raw {
        label: string;
        target_port?: number | null;
        port_range?: serializers.cloud.version.matchmaker.PortRange.Raw | null;
        proxy_protocol: serializers.cloud.version.matchmaker.PortProtocol.Raw;
    }
}
