/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthRefreshIdentityTokenResponse {
    /// Token expiration time (in milliseconds).
    #[serde(rename = "exp")]
    pub exp: String,
    #[serde(rename = "identity_id")]
    pub identity_id: uuid::Uuid,
    /// A JSON Web Token. Slightly modified to include a description prefix and use Protobufs of JSON.
    #[serde(rename = "token")]
    pub token: String,
}

impl AuthRefreshIdentityTokenResponse {
    pub fn new(exp: String, identity_id: uuid::Uuid, token: String) -> AuthRefreshIdentityTokenResponse {
        AuthRefreshIdentityTokenResponse {
            exp,
            identity_id,
            token,
        }
    }
}


