/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ActorGuardRouting {
    #[serde(rename = "authorization", skip_serializing_if = "Option::is_none")]
    pub authorization: Option<Box<crate::models::ActorPortAuthorization>>,
}

impl ActorGuardRouting {
    pub fn new() -> ActorGuardRouting {
        ActorGuardRouting {
            authorization: None,
        }
    }
}


