/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ActorsLogsExportRequest {
	#[serde(rename = "project", skip_serializing_if = "Option::is_none")]
	pub project: Option<String>,
	#[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
	pub environment: Option<String>,
	/// JSON-encoded query expression for filtering logs
	#[serde(rename = "query_json")]
	pub query_json: String,
}

impl ActorsLogsExportRequest {
	pub fn new(query_json: String) -> ActorsLogsExportRequest {
		ActorsLogsExportRequest {
			project: None,
			environment: None,
			query_json,
		}
	}
}
