/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BuildsPrepareBuildResponse {
    #[serde(rename = "build")]
    pub build: uuid::Uuid,
    #[serde(rename = "presigned_requests")]
    pub presigned_requests: Vec<crate::models::UploadPresignedRequest>,
}

impl BuildsPrepareBuildResponse {
    pub fn new(build: uuid::Uuid, presigned_requests: Vec<crate::models::UploadPresignedRequest>) -> BuildsPrepareBuildResponse {
        BuildsPrepareBuildResponse {
            build,
            presigned_requests,
        }
    }
}


