/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// CloudCdnSiteSummary : A CDN site summary.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudCdnSiteSummary {
	#[serde(rename = "site_id")]
	pub site_id: uuid::Uuid,
	#[serde(rename = "upload_id")]
	pub upload_id: uuid::Uuid,
	/// Represent a resource's readable display name.
	#[serde(rename = "display_name")]
	pub display_name: String,
	/// RFC3339 timestamp
	#[serde(rename = "create_ts")]
	pub create_ts: String,
	/// Unsigned 64 bit integer.
	#[serde(rename = "content_length")]
	pub content_length: i64,
	/// Whether or not this site has completely been uploaded.
	#[serde(rename = "complete")]
	pub complete: bool,
}

impl CloudCdnSiteSummary {
	/// A CDN site summary.
	pub fn new(
		site_id: uuid::Uuid,
		upload_id: uuid::Uuid,
		display_name: String,
		create_ts: String,
		content_length: i64,
		complete: bool,
	) -> CloudCdnSiteSummary {
		CloudCdnSiteSummary {
			site_id,
			upload_id,
			display_name,
			create_ts,
			content_length,
			complete,
		}
	}
}
