/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// IdentityProfile : An identity profile.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityProfile {
	#[serde(rename = "identity_id")]
	pub identity_id: uuid::Uuid,
	/// Represent a resource's readable display name.
	#[serde(rename = "display_name")]
	pub display_name: String,
	#[serde(rename = "account_number")]
	pub account_number: i32,
	/// The URL of this identity's avatar image.
	#[serde(rename = "avatar_url")]
	pub avatar_url: String,
	/// Whether or not this identity is registered with a linked account.
	#[serde(rename = "is_registered")]
	pub is_registered: bool,
	#[serde(rename = "external")]
	pub external: Box<crate::models::IdentityExternalLinks>,
	/// Whether or not this identity is an admin.
	#[serde(rename = "is_admin")]
	pub is_admin: bool,
	/// Whether or not this game user has been linked through the Rivet dashboard.
	#[serde(rename = "is_game_linked", skip_serializing_if = "Option::is_none")]
	pub is_game_linked: Option<bool>,
	#[serde(rename = "dev_state", skip_serializing_if = "Option::is_none")]
	pub dev_state: Option<crate::models::IdentityDevState>,
	#[serde(rename = "follower_count")]
	pub follower_count: i64,
	#[serde(rename = "following_count")]
	pub following_count: i64,
	/// Whether or not the requestee's identity is following this identity.
	#[serde(rename = "following")]
	pub following: bool,
	/// Whether or not this identity is both following and is followed by the requestee's identity.
	#[serde(rename = "is_following_me")]
	pub is_following_me: bool,
	#[serde(rename = "is_mutual_following")]
	pub is_mutual_following: bool,
	/// RFC3339 timestamp
	#[serde(rename = "join_ts")]
	pub join_ts: String,
	/// Follows regex ^(?:[^\\n\\r]+\\n?|\\n){1,5}$
	#[serde(rename = "bio")]
	pub bio: String,
	#[serde(rename = "linked_accounts")]
	pub linked_accounts: Vec<crate::models::IdentityLinkedAccount>,
	#[serde(rename = "groups")]
	pub groups: Vec<crate::models::IdentityGroup>,
	#[serde(rename = "games")]
	pub games: Vec<crate::models::GameStatSummary>,
	/// Whether or not this identity is awaiting account deletion. Only visible to when the requestee is this identity.
	#[serde(rename = "awaiting_deletion", skip_serializing_if = "Option::is_none")]
	pub awaiting_deletion: Option<bool>,
}

impl IdentityProfile {
	/// An identity profile.
	pub fn new(
		identity_id: uuid::Uuid,
		display_name: String,
		account_number: i32,
		avatar_url: String,
		is_registered: bool,
		external: crate::models::IdentityExternalLinks,
		is_admin: bool,
		follower_count: i64,
		following_count: i64,
		following: bool,
		is_following_me: bool,
		is_mutual_following: bool,
		join_ts: String,
		bio: String,
		linked_accounts: Vec<crate::models::IdentityLinkedAccount>,
		groups: Vec<crate::models::IdentityGroup>,
		games: Vec<crate::models::GameStatSummary>,
	) -> IdentityProfile {
		IdentityProfile {
			identity_id,
			display_name,
			account_number,
			avatar_url,
			is_registered,
			external: Box::new(external),
			is_admin,
			is_game_linked: None,
			dev_state: None,
			follower_count,
			following_count,
			following,
			is_following_me,
			is_mutual_following,
			join_ts,
			bio,
			linked_accounts,
			groups,
			games,
			awaiting_deletion: None,
		}
	}
}
