/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProvisionServersGetInfoResponse {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "server_id")]
    pub server_id: uuid::Uuid,
    #[serde(rename = "datacenter_id")]
    pub datacenter_id: uuid::Uuid,
    #[serde(rename = "datacenter_name_id")]
    pub datacenter_name_id: String,
    #[serde(rename = "cluster_id")]
    pub cluster_id: uuid::Uuid,
    #[serde(rename = "lan_ip")]
    pub lan_ip: String,
    #[serde(rename = "wan_ip")]
    pub wan_ip: String,
    /// **Deprecated**: Use lan_ip
    #[serde(rename = "vlan_ip")]
    pub vlan_ip: String,
    /// **Deprecated**: Use wan_ip
    #[serde(rename = "public_ip")]
    pub public_ip: String,
}

impl ProvisionServersGetInfoResponse {
    pub fn new(name: String, server_id: uuid::Uuid, datacenter_id: uuid::Uuid, datacenter_name_id: String, cluster_id: uuid::Uuid, lan_ip: String, wan_ip: String, vlan_ip: String, public_ip: String) -> ProvisionServersGetInfoResponse {
        ProvisionServersGetInfoResponse {
            name,
            server_id,
            datacenter_id,
            datacenter_name_id,
            cluster_id,
            lan_ip,
            wan_ip,
            vlan_ip,
            public_ip,
        }
    }
}


