/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as Rivet from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const GetGameLinkNewIdentity: core.serialization.ObjectSchema<serializers.identity.GetGameLinkNewIdentity.Raw, Rivet.identity.GetGameLinkNewIdentity>;
export declare namespace GetGameLinkNewIdentity {
    interface Raw {
        identity_token: serializers.Jwt.Raw;
        identity_token_expire_ts: serializers.Timestamp.Raw;
        identity: serializers.identity.Profile.Raw;
    }
}
