/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Timestamp } from "../../../../common/types/Timestamp";
import { WatchResponse } from "../../../../common/types/WatchResponse";

export const GetActorLogsResponse: core.serialization.ObjectSchema<
    serializers.actors.GetActorLogsResponse.Raw,
    Rivet.actors.GetActorLogsResponse
> = core.serialization.object({
    actorIds: core.serialization.property("actor_ids", core.serialization.list(core.serialization.string())),
    lines: core.serialization.list(core.serialization.string()),
    timestamps: core.serialization.list(Timestamp),
    streams: core.serialization.list(core.serialization.number()),
    actorIndices: core.serialization.property("actor_indices", core.serialization.list(core.serialization.number())),
    watch: WatchResponse,
});

export declare namespace GetActorLogsResponse {
    interface Raw {
        actor_ids: string[];
        lines: string[];
        timestamps: Timestamp.Raw[];
        streams: number[];
        actor_indices: number[];
        watch: WatchResponse.Raw;
    }
}
