/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../../../index";

/**
 * @example
 *     {
 *         project: "string",
 *         environment: "string",
 *         body: {
 *             name: "string",
<<<<<<< HEAD
=======
 *             tags: {
 *                 "key": "value"
 *             },
>>>>>>> 73a068837 (feat: revamp actor build endpoint, js builds -> tar)
 *             imageTag: "string",
 *             imageFile: {
 *                 path: "string",
 *                 contentType: "string",
 *                 contentLength: 1000000
 *             },
 *             multipartUpload: true,
 *             kind: "docker_image",
 *             compression: "none",
 *             prewarmRegions: ["string"]
 *         }
 *     }
 */
export interface PrepareBuildRequestQuery {
    project?: string;
    environment?: string;
    body: Rivet.actor.PrepareBuildRequest;
}
