[package]
name = "api-admin"
version = "0.0.1"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
rivet-convert = { path = "../../../lib/convert" }
api-helper = { path = "../../../lib/api-helper/build" }
async_once = "0.2"
async-trait = "0.1"
chirp-client = { path = "../../../lib/chirp/client" }
chirp-workflow = { path = "../../../lib/chirp-workflow/core" }
rivet-operation = { path = "../../../lib/operation/core" }
chrono = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
lazy_static = "1.4"
prost = "0.10"
reqwest = "0.11"
rivet-api = { path = "../../../sdks/full/rust" }
rivet-cache = { path = "../../../lib/cache/build" }
rivet-claims = { path = "../../../lib/claims" }
rivet-health-checks = { path = "../../../lib/health-checks" }
rivet-matchmaker = { path = "../../../lib/smithy-output/api-matchmaker/rust" }
rivet-pools = { path = "../../../lib/pools" }
s3-util = { path = "../../../lib/s3-util" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.29" }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
url = "2.2.2"
uuid = { version = "1", features = ["v4"] }
util-mm = { package = "rivet-util-mm", path = "../../pkg/mm/util" }

cluster = { path = "../../pkg/cluster" }
token-create = { path = "../../pkg/token/ops/create" }

[dev-dependencies]
rivet-connection = { path = "../../../lib/connection" }
