/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const Distance: core.serialization.ObjectSchema<serializers.geo.Distance.Raw, Rivet.geo.Distance> =
    core.serialization.object({
        kilometers: core.serialization.number(),
        miles: core.serialization.number(),
    });

export declare namespace Distance {
    interface Raw {
        kilometers: number;
        miles: number;
    }
}
