/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../index";
import * as Rivet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
export declare const CustomAvatar: core.serialization.ObjectSchema<serializers.cloud.version.identity.CustomAvatar.Raw, Rivet.cloud.version.identity.CustomAvatar>;
export declare namespace CustomAvatar {
    interface Raw {
        upload_id: string;
    }
}
