/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";

export const EmptyObject: core.serialization.ObjectSchema<serializers.EmptyObject.Raw, Rivet.EmptyObject> =
    core.serialization.object({});

export declare namespace EmptyObject {
    interface Raw {}
}
