/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../..";

export interface PrepareAvatarUploadResponse {
    uploadId: string;
    presignedRequest: Rivet.upload.PresignedRequest;
}
