/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const PortProtocol: core.serialization.Schema<serializers.servers.PortProtocol.Raw, Rivet.servers.PortProtocol> =
    core.serialization.enum_(["http", "https", "tcp", "tcp_tls", "udp"]);

export declare namespace PortProtocol {
    export type Raw = "http" | "https" | "tcp" | "tcp_tls" | "udp";
}
