/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../index";

export interface CreateActorRequest {
    region: string;
    tags?: unknown;
    runtime: Rivet.actor.CreateActorRuntimeRequest;
    network?: Rivet.actor.CreateActorNetworkRequest;
    resources: Rivet.actor.Resources;
    lifecycle?: Rivet.actor.Lifecycle;
}
