/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Rivet from "../../../../api";
import * as core from "../../../../core";
export declare const BootstrapCaptcha: core.serialization.ObjectSchema<serializers.cloud.BootstrapCaptcha.Raw, Rivet.cloud.BootstrapCaptcha>;
export declare namespace BootstrapCaptcha {
    interface Raw {
        turnstile?: serializers.cloud.BootstrapCaptchaTurnstile.Raw | null;
    }
}
