/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../../../../index";

export interface Actor {
    id: string;
    region: string;
    tags?: unknown;
    runtime: Rivet.actors.v1.Runtime;
    network: Rivet.actors.v1.Network;
    resources?: Rivet.actors.v1.Resources;
    lifecycle: Rivet.actors.v1.Lifecycle;
    createdAt: Rivet.Timestamp;
    startedAt?: Rivet.Timestamp;
    destroyedAt?: Rivet.Timestamp;
}
