/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A CDN site summary.
 */
export interface CdnSiteSummary {
    siteId: string;
    uploadId: string;
    /** Represent a resource's readable display name. */
    displayName: string;
    /** RFC3339 timestamp. */
    createTs: Date;
    /** Unsigned 64 bit integer. */
    contentLength: number;
    /** Whether or not this site has completely been uploaded. */
    complete: boolean;
}
