/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GlobalEventNotification {
    title: string;
    description: string;
    thumbnailUrl: string;
    url: string;
}
