/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GetInfoResponse {
    name: string;
    serverId: string;
    datacenterId: string;
    clusterId: string;
    vlanIp: string;
}
