#!/bin/sh
mkdir -p /data/rivet-client
mkdir -p /var/log/rivet-client
chown nobody:nogroup /var/log/rivet-client
chmod 02755 /var/log/rivet-client
mkdir -p /data/cockroachdb
chown cockroachdb:cockroachdb /data/cockroachdb
mkdir -p /var/log/cockroachdb
chown nobody:nogroup /var/log/cockroachdb
chmod 02755 /var/log/cockroachdb
mkdir -p /data/redis
chown redis:redis /data/redis
mkdir -p /var/log/redis
chown nobody:nogroup /var/log/redis
chmod 02755 /var/log/redis
mkdir -p /data/clickhouse
chown clickhouse:clickhouse /data/clickhouse
mkdir -p /var/log/clickhouse
chown nobody:nogroup /var/log/clickhouse
chmod 02755 /var/log/clickhouse
mkdir -p /var/log/nats
chown nobody:nogroup /var/log/nats
chmod 02755 /var/log/nats
mkdir -p /data/seaweedfs
chown seaweedfs:seaweedfs /data/seaweedfs
mkdir -p /var/log/seaweedfs
chown nobody:nogroup /var/log/seaweedfs
chmod 02755 /var/log/seaweedfs
mkdir -p /data/vector-client
chown vector-client:vector-client /data/vector-client
mkdir -p /var/log/vector-client
chown nobody:nogroup /var/log/vector-client
chmod 02755 /var/log/vector-client
mkdir -p /data/vector-server
chown vector-server:vector-server /data/vector-server
mkdir -p /var/log/vector-server
chown nobody:nogroup /var/log/vector-server
chmod 02755 /var/log/vector-server
