/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         anchor: "string",
 *         limit: 1
 *     }
 */
export interface GetGameNamespaceVersionHistoryRequest {
    /**
     * How many items to offset the search by.
     */
    anchor?: string;
    /**
     * Amount of items to return. Must be between 1 and 32 inclusive.
     */
    limit?: number;
}
