/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         gameId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
 *         environmentId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
 *         overrideKillTimeout: 1000000
 *     }
 */
export interface DestroyActorRequestQuery {
    gameId?: string;
    environmentId?: string;
    /**
     * The duration to wait for in milliseconds before killing the actor. This should be used to override the default kill timeout if a faster time is needed, say for ignoring a graceful shutdown.
     */
    overrideKillTimeout?: number;
}
