/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Rivet from "../../..";
export interface UpdateProfileRequest {
    displayName?: Rivet.DisplayName;
    /** Detailed information about a profile. */
    bio?: string;
    publicity?: Rivet.group.Publicity;
}
