/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamespacesGetResponse {
    #[serde(rename = "namespace")]
    pub namespace: Box<models::Namespace>,
}

impl NamespacesGetResponse {
    pub fn new(namespace: models::Namespace) -> NamespacesGetResponse {
        NamespacesGetResponse {
            namespace: Box::new(namespace),
        }
    }
}

