/*
 * rivet-api-public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 25.7.0
 * Contact: developer@rivet.gg
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerConfigsListResponse {
    #[serde(rename = "pagination")]
    pub pagination: Box<models::Pagination>,
    #[serde(rename = "runner_configs")]
    pub runner_configs: std::collections::HashMap<String, models::RunnerConfig>,
}

impl RunnerConfigsListResponse {
    pub fn new(pagination: models::Pagination, runner_configs: std::collections::HashMap<String, models::RunnerConfig>) -> RunnerConfigsListResponse {
        RunnerConfigsListResponse {
            pagination: Box::new(pagination),
            runner_configs,
        }
    }
}

