/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../../../index";
import * as Rivet from "../../../../../../../../../../api/index";
import * as core from "../../../../../../../../../../core";
import { CaptchaHcaptcha } from "./CaptchaHcaptcha";
import { CaptchaTurnstile } from "./CaptchaTurnstile";
export declare const Captcha: core.serialization.ObjectSchema<serializers.cloud.version.matchmaker.Captcha.Raw, Rivet.cloud.version.matchmaker.Captcha>;
export declare namespace Captcha {
    interface Raw {
        requests_before_reverify: number;
        verification_ttl: number;
        hcaptcha?: CaptchaHcaptcha.Raw | null;
        turnstile?: CaptchaTurnstile.Raw | null;
    }
}
