/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../../../index";
import * as Rivet from "../../../../../../../../../../api/index";
import * as core from "../../../../../../../../../../core";
export declare const PortRange: core.serialization.ObjectSchema<serializers.cloud.version.matchmaker.PortRange.Raw, Rivet.cloud.version.matchmaker.PortRange>;
export declare namespace PortRange {
    interface Raw {
        min: number;
        max: number;
    }
}
