/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Rivet from "../../../../api/index";
import * as core from "../../../../core";
import { Container } from "../resources/common/types/Container";

export const GetContainerResponse: core.serialization.ObjectSchema<
    serializers.containers.GetContainerResponse.Raw,
    Rivet.containers.GetContainerResponse
> = core.serialization.object({
    container: Container,
});

export declare namespace GetContainerResponse {
    export interface Raw {
        container: Container.Raw;
    }
}
