/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Rivet from "../../../../..";
/**
 * The status of a stopped lobby.
 */
export interface LogsLobbyStatusStopped {
    stopTs: Rivet.Timestamp;
    /** Whether or not the lobby failed or stopped successfully. */
    failed: boolean;
    /** The exit code returned by the lobby's main process when stopped. */
    exitCode: number;
}
