/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../..";
import * as Rivet from "../../../../../../../../api";
import * as core from "../../../../../../../../core";
export declare const CreateGameNamespaceTokenServiceRequest: core.serialization.ObjectSchema<serializers.cloud.games.namespaces.CreateGameNamespaceTokenServiceRequest.Raw, Rivet.cloud.games.namespaces.CreateGameNamespaceTokenServiceRequest>;
export declare namespace CreateGameNamespaceTokenServiceRequest {
    interface Raw {
        ttl: number;
    }
}
