/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../../../index";
import * as Rivet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { cloud } from "../../../../../../index";
export declare const SetNamespaceCdnAuthTypeRequest: core.serialization.ObjectSchema<serializers.cloud.games.namespaces.SetNamespaceCdnAuthTypeRequest.Raw, Rivet.cloud.games.namespaces.SetNamespaceCdnAuthTypeRequest>;
export declare namespace SetNamespaceCdnAuthTypeRequest {
    interface Raw {
        auth_type: cloud.CdnAuthType.Raw;
    }
}
