/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { matchmaker } from "../../../../index";
export declare const JoinLobby: core.serialization.ObjectSchema<serializers.matchmaker.JoinLobby.Raw, Rivet.matchmaker.JoinLobby>;
export declare namespace JoinLobby {
    interface Raw {
        lobby_id: string;
        region: matchmaker.JoinRegion.Raw;
        ports: Record<string, matchmaker.JoinPort.Raw>;
        player: matchmaker.JoinPlayer.Raw;
    }
}
