/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../..";
import * as Rivet from "../../../../../../api";
import * as core from "../../../../../../core";
export declare const RegionInfo: core.serialization.ObjectSchema<serializers.matchmaker.RegionInfo.Raw, Rivet.matchmaker.RegionInfo>;
export declare namespace RegionInfo {
    interface Raw {
        region_id: serializers.Identifier.Raw;
        provider_display_name: serializers.DisplayName.Raw;
        region_display_name: serializers.DisplayName.Raw;
        datacenter_coord: serializers.geo.Coord.Raw;
        datacenter_distance_from_client: serializers.geo.Distance.Raw;
    }
}
