import { Accordion } from "@/components/Accordion";
import { Heading } from "@/components/Heading";
import {
	Icon,
	faExclamationTriangle,
	faInfoCircle,
	faLightbulbOn,
} from "@rivet-gg/icons";
import NextImage from "next/image";
import Link from "next/link";

export { ButtonGroup, Button } from "@/components/Button";
export { ResourceGroup, Resource } from "@/components/Resources";
export { Snippet } from "@/components/Snippet";
export { Summary } from "@/components/Summary";
export { Accordion, AccordionGroup } from "@/components/Accordion";
export * from "@/components/callouts";
export { ArticleHeader } from "@/components/ArticleHeader";
export { ArticleSocials } from "@/components/ArticleSocials";
import { CodeBlock } from "@/components/CodeBlock";
import {
	Alert,
	AlertDescription,
	AlertTitle,
	Badge,
	CtaCard,
	WithTooltip,
} from "@rivet-gg/components";

import { SchemaPreview as Schema } from "@/components/SchemaPreview";

export * from "@rivet-gg/components/mdx";
export const a = Link;

export const Image = (props) => <NextImage {...props} />;

export const h2 = function H2(props) {
	return <Heading level={2} {...props} />;
};

export const h3 = function H3(props) {
	return <Heading level={3} {...props} />;
};

export const table = function Table(props) {
	return (
		<div className="overflow-x-auto">
			<table {...props} />
		</div>
	);
};

export function Tooltip({ tip, children }) {
	return (
		<WithTooltip
			content={tip}
			trigger={
				<span className="underline decoration-cream-400 decoration-dotted decoration-2 underline-offset-4 dark:decoration-charcole-500">
					{children}
				</span>
			}
		/>
	);
}

export function ComingSoon() {
	return <Note>Documentation coming very soon!</Note>;
}

export function Outdated() {
	return (
		<Info>
			🚧 This documentation page is no longer maintained and potentially
			outdated 🚧
		</Info>
	);
}

export function WorkInProgress() {
	return <Info>🚧 This documentation page is a work in progress 🚧</Info>;
}

export function EnvTokenClient() {
	return (
		<Info>
			<p>
				In development,&nbsp;<code>RIVET_TOKEN</code> will use the
				development token generated by <code>rivet run</code>. In
				production,&nbsp;<code>RIVET_TOKEN</code> will be automatically
				added by the CDN.
			</p>

			<p>More info:</p>

			<ul>
				<li>
					<Link href="/docs/general/concepts/handling-game-tokens">
						Handling game tokens
					</Link>
				</li>
				<li>
					<Link href="/docs/general/concepts/dev-tokens">
						Development tokens
					</Link>
				</li>
				<li>
					<Link href="/docs/general/concepts/token-types#namespace-public">
						Public tokens
					</Link>
				</li>
			</ul>
		</Info>
	);
}

export function EnvTokenServer() {
	return (
		<Info>
			<p>
				In development, <code>RIVET_TOKEN</code> will use the
				development token generated by <code>rivet run</code>. In
				production,&nbsp;<code>RIVET_TOKEN</code> is automatically added
				to your environment by Rivet.
			</p>

			<p>More info:</p>

			<ul>
				<li>
					<Link href="/docs/general/concepts/handling-game-tokens">
						Handling game tokens
					</Link>
				</li>
				<li>
					<Link href="/docs/general/concepts/dev-tokens">
						Development tokens
					</Link>
				</li>
			</ul>
		</Info>
	);
}

export function PreRivetBranch() {
	return (
		<Info>
			<p>
				The <code>pre-rivet</code> branch contains the source code of
				this project without Rivet implemented, in contrast to the{" "}
				<code>main</code> branch. View these side by side to get a good
				picture of what it takes to integrate Rivet for your game.
			</p>
		</Info>
	);
}

export function ProtocolSupportMatrix() {
	return (
		<table>
			<tr>
				<th>Protocol</th>
				<th>
					<Link href="/docs/general/dynamic-servers/game-guard">
						Rivet Game Guard
					</Link>
				</th>
				<th>
					<Link href="/docs/general/dynamic-servers/host-bridge-networking">
						Host Network (Open Source & Enterprise)
					</Link>
				</th>
			</tr>
			<tr>
				<td></td>
				<td>
					<em>Requires single port</em>
				</td>
				<td>
					<em>Requires port range</em>
				</td>
			</tr>
			<tr>
				<td>HTTPS / Secure WebSocket</td>
				<td>✅</td>
				<td></td>
			</tr>
			<tr>
				<td>HTTP / WebSocket</td>
				<td>✅</td>
				<td></td>
			</tr>
			<tr>
				<td>TCP + TLS</td>
				<td>✅</td>
				<td></td>
			</tr>
			<tr>
				<td>TCP</td>
				<td>✅</td>
				<td>✅</td>
			</tr>
			<tr>
				<td>UDP / WebRTC / ENet / KCP</td>
				<td>✅</td>
				<td>✅</td>
			</tr>
		</table>
	);
}

export function InstallCli() {
	return (
		<Note>
			Make sure you have installed the Rivet CLI{" "}
			<Link
				href="https://github.com/rivet-gg/cli#installing"
				target="_blank"
			>
				here
			</Link>
			.
		</Note>
	);
}

export function AutomateWithApi() {
	return (
		<Accordion title="Can I automate this with APIs?">
			<p>
				Rivet&apos;s Cloud API can be managed with your{" "}
				<Link href="/docs/general/concepts/token-types#cloud">
					cloud token
				</Link>
				. This is the same API we use internally and{" "}
				<Link href="https://github.com/rivet-gg/cli/blob/7f91d180f64b755956d89a3a83bfb2e77a42d72d/cli/src/commands/version.rs#L368">
					in the CLI
				</Link>
				.
			</p>

			<p>
				The Cloud REST API is documented{" "}
				<Link href="/docs/cloud">here</Link>. You can also use the{" "}
				<Link
					href="https://www.npmjs.com/package/@rivet-gg/api-full"
					target="_blank"
				>
					<code>@rivet-gg/api-full</code> NPM library
				</Link>{" "}
				to interact with the Cloud API.
			</p>
		</Accordion>
	);
}

export function CrashCourseUnrealBlueprint() {
	return null;
	return (
		<Tip>
			<p>TODO: Unreal crash blueprints course</p>
			<ul>
				<li>Comments</li>
				<li>3 ways to create nodes</li>
			</ul>
		</Tip>
	);
}

export function CrashCourseUnrealWidget() {
	return null;
	return (
		<Tip>
			<p>TODO: Unreal crash blueprints course</p>
			<ul>
				<li>How to create a UI</li>
				<li>Common widget types</li>
			</ul>
		</Tip>
	);
}

export function UnfamiliarWithDockerfiles() {
	return (
		<Accordion title="Unfamiliar with Dockerfiles?">
			<ul>
				<li>
					<a href="https://github.com/gauthamp10/dockerfile-boilerplates">
						Boilerplate <code>Dockerfiles</code>
					</a>{" "}
					has one already written for you
				</li>
				<li>
					<a href="https://docker-curriculum.com/#dockerfile">
						Dockerfile Crash Course
					</a>{" "}
					will teach you how to write your own <code>Dockerfile</code>{" "}
					quickly
				</li>
				<li>
					Join our <a href="https://discord.gg/BG2vqsJczH">Discord</a>{" "}
					and we&apos;ll write your <code>Dockerfile</code> for you!
				</li>
			</ul>
		</Accordion>
	);
}

export const ExperimentalFeature = () => {
	return (
		<Warning>
			This feature is experimental and may change in the future.
		</Warning>
	);
};

export const Version = () => {
	const version = "0.1.5";
	return (
		<CodeBlock
			lang="bash"
			code={`deno install -n opengb -fgA https://raw.githubusercontent.com/rivet-gg/opengb/v${version}/src/cli/main.ts`}
		/>
	);
};

export const Card = ({ href, ...props }) => {
	if (href) {
		return (
			<Link href={href} className="h-full">
				<CtaCard className="h-full" {...props} />
			</Link>
		);
	}
};

export const CardGroup = ({ children }) => {
	return (
		<div className="not-prose grid gap-4 md:grid-cols-2">{children}</div>
	);
};

export const SchemaPreview = ({ schema }) => {
	return (
		<div className="not-prose rounded-md border p-4">
			<Schema schema={schema} />
		</div>
	);
};

export const Warning = ({ title = "Notice", children }) => {
	return (
		<Alert variant="warning" className="my-4">
			<AlertTitle className="flex items-center">
				<Icon
					icon={faExclamationTriangle}
					className="mr-2 text-warning"
				/>
				{title}
			</AlertTitle>
			<AlertDescription className="prose-invert prose">
				{children}
			</AlertDescription>
		</Alert>
	);
};

export const Tip = ({ title = "Tip", children }) => {
	return (
		<Alert className="my-4">
			<AlertTitle className="flex items-center">
				<Icon icon={faLightbulbOn} className="mr-2 text-primary" />
				{title}
			</AlertTitle>
			<AlertDescription className="prose-invert prose">
				{children}
			</AlertDescription>
		</Alert>
	);
};

export const Info = ({ title = "Info", children }) => {
	return (
		<Alert className="my-4">
			<AlertTitle className="flex items-center">
				<Icon icon={faInfoCircle} className="mr-2" />
				{title}
			</AlertTitle>
			<AlertDescription className="prose-invert prose">
				{children}
			</AlertDescription>
		</Alert>
	);
};

export const Note = ({ title = "Note", children }) => {
	return (
		<Alert variant="info" className="my-4">
			<AlertTitle className="prose-invert flex items-center [&_p]:first-of-type:my-0">
				<Icon icon={faInfoCircle} className="mr-2" />
				{title}
			</AlertTitle>
			<AlertDescription className="prose-invert prose">
				{children}
			</AlertDescription>
		</Alert>
	);
};

export const Tags = ({ tags }) => {
	return (
		<div className="flex flex-wrap gap-1">
			{tags.map((tag) => (
				<Badge key={tag}>{tag}</Badge>
			))}
		</div>
	);
};

export const Lead = ({ children }) => {
	return <p class="mb-10 text-lg font-semibold leading-7">{children}</p>;
};
export { Step, Steps } from "@rivet-gg/components";

export const HideOnHub = ({ children }) => children;

export function DownloadTemplate({ href }) {
	return (
		<div className="not-prose mb-16 mt-6 flex gap-3">
			<a
				href={href}
				className="inline-flex items-center gap-2 rounded-lg bg-black px-4 py-2 text-sm font-medium text-white hover:bg-[#292524] border border-white/20 hover:border-transparent"
			>
				<svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5 fill-white">
					<path fillRule="evenodd" clipRule="evenodd" d="M12 2C6.477 2 2 6.463 2 11.97c0 4.404 2.865 8.14 6.839 9.458.5.092.682-.216.682-.48 0-.236-.008-.864-.013-1.695-2.782.602-3.369-1.337-3.369-1.337-.454-1.151-1.11-1.458-1.11-1.458-.908-.618.069-.606.069-.606 1.003.07 1.531 1.027 1.531 1.027.892 1.524 2.341 1.084 2.91.828.092-.643.35-1.083.636-1.332-2.22-.251-4.555-1.107-4.555-4.927 0-1.088.39-1.979 1.029-2.675-.103-.252-.446-1.266.098-2.638 0 0 .84-.268 2.75 1.022A9.607 9.607 0 0 1 12 6.82c.85.004 1.705.114 2.504.336 1.909-1.29 2.747-1.022 2.747-1.022.546 1.372.202 2.386.1 2.638.64.696 1.028 1.587 1.028 2.675 0 3.83-2.339 4.673-4.566 4.92.359.307.678.915.678 1.846 0 1.332-.012 2.407-.012 2.734 0 .267.18.577.688.48 3.97-1.32 6.833-5.054 6.833-9.458C22 6.463 17.522 2 12 2Z"></path>
				</svg>
				Download Template
			</a>
		</div>
	);
}
