/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../..";

/**
 * A performance mark.
 */
export interface LogsPerfMark {
    /** The label given to this performance mark. */
    label: string;
    ts: Rivet.Timestamp;
    rayId?: string;
    reqId?: string;
}
