/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Rivet from "../../../../../../api";
import * as core from "../../../../../../core";

export const GetGameByIdResponse: core.serialization.ObjectSchema<
    serializers.cloud.games.GetGameByIdResponse.Raw,
    Rivet.cloud.games.GetGameByIdResponse
> = core.serialization.object({
    game: core.serialization.lazyObject(async () => (await import("../../../../..")).cloud.GameFull),
    watch: core.serialization.lazyObject(async () => (await import("../../../../..")).WatchResponse),
});

export declare namespace GetGameByIdResponse {
    interface Raw {
        game: serializers.cloud.GameFull.Raw;
        watch: serializers.WatchResponse.Raw;
    }
}
