/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LogStream = "std_out" | "std_err";

export const LogStream = {
    StdOut: "std_out",
    StdErr: "std_err",
} as const;
