/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../../index";
import * as Rivet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Handle } from "../../../../group/resources/common/types/Handle";
export declare const Group: core.serialization.ObjectSchema<serializers.identity.Group.Raw, Rivet.identity.Group>;
export declare namespace Group {
    interface Raw {
        group: Handle.Raw;
    }
}
