/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Rivet from "../../../../index";
/**
 * @example
 *     {
 *         watchIndex: "string"
 *     }
 */
export interface GetProfileRequest {
    watchIndex?: Rivet.WatchQuery;
}
