/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Rivet from "../../../../api";
import * as core from "../../../../core";

export const GetProfileResponse: core.serialization.ObjectSchema<
    serializers.identity.GetProfileResponse.Raw,
    Rivet.identity.GetProfileResponse
> = core.serialization.object({
    identity: core.serialization.lazyObject(async () => (await import("../../..")).identity.Profile),
    watch: core.serialization.lazyObject(async () => (await import("../../..")).WatchResponse),
});

export declare namespace GetProfileResponse {
    interface Raw {
        identity: serializers.identity.Profile.Raw;
        watch: serializers.WatchResponse.Raw;
    }
}
